replicaCount: 2

image:
  repository: wagnermh/ion-desafio-devops-app
  pullPolicy: Always
  tag: "1.9" #"latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: ion-app.local
      paths:
        - path: /
          pathType: Prefix
